[default.extend-words]
# Used intentionally in helpcount eval scenarios (a realistic flag typo).
prety = "prety"
# More intentional typos used in helpcount eval scenarios.
stauts = "stauts"
verison = "verison"
fial = "fial"
protocl = "protocl"
